# Generated by Django 5.2.8 on 2025-12-23 17:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300)),
                ('montant', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('chemise', 'Chemises'), ('pantalon', 'Pantalons'), ('robe', 'Robes'), ('jupe', 'Jupes'), ('tshirt', 'T-shirts'), ('pull', 'Pulls'), ('veste', 'Vestes'), ('manteau', 'Manteaux'), ('short', 'Shorts'), ('corsage', 'Corsages'), ('drap', 'Draps'), ('costume', 'Costumes'), ('cravate', 'Cravates'), ('autre', 'Autres')], max_length=50)),
                ('quantite', models.PositiveIntegerField()),
                ('prix_lavage_repassage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('prix_repassage', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('delai', models.CharField(choices=[('normal', 'Normal'), ('express', 'Express')], max_length=40)),
                ('statut', models.CharField(choices=[('paye_livre', 'Payé/Livré'), ('paye', 'Payé/Non Livré'), ('non_paye', 'Non Payé')], max_length=40)),
                ('total', models.FloatField(default=0.0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='DetailCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('option', models.CharField(choices=[('lavage_repassage', 'Lavage et Repassage'), ('repassage_seul', 'Repassage seul')], max_length=40)),
                ('prix', models.FloatField(default=0.0)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_app.commande')),
                ('vetement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pressing_app.vetement')),
            ],
        ),
    ]
