# Generated by Django 5.2.8 on 2025-12-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing_app', '0002_alter_detailcommande_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vetement',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='detailcommande',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
