# Generated by Django 5.2.8 on 2025-12-23 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pressing_app', '0003_remove_vetement_quantite_alter_commande_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailcommande',
            name='prix',
        ),
    ]
