# Generated by Django 5.2.8 on 2025-12-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing_app', '0004_remove_detailcommande_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='statut',
        ),
        migrations.AddField(
            model_name='commande',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='commande',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('paye_livre', 'Payé/Livré'), ('paye_non_livre', 'Payé/Non Livré'), ('non_paye_non_livre', 'Non Payé/Non livre')], default='on_paye_non_livre', max_length=600),
        ),
        migrations.AddField(
            model_name='detailcommande',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='commande',
            name='delai',
            field=models.CharField(choices=[('normal', 'Normal'), ('express', 'Express')], default='normal', max_length=600),
        ),
        migrations.AlterField(
            model_name='commande',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='detailcommande',
            name='option',
            field=models.CharField(choices=[('lavage_repassage', 'Lavage et Repassage'), ('repassage_seul', 'Repassage seul')], max_length=600),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
