# Generated by Django 5.2.8 on 2025-12-31 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing_app', '0005_remove_commande_statut_commande_montant_paye_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='etat',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('confirmee', 'Confirmée')], default='brouillon', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='delai',
            field=models.CharField(choices=[('normal', 'Normal'), ('express', 'Express')], default='normal', max_length=60),
        ),
        migrations.AlterField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('paye_livre', 'Payé/Livré'), ('paye_non_livre', 'Payé/Non Livré'), ('non_paye_non_livre', 'Non Payé/Non livre')], default='non_paye_non_livre', max_length=60),
        ),
        migrations.AlterField(
            model_name='detailcommande',
            name='option',
            field=models.CharField(choices=[('lavage_repassage', 'Lavage et Repassage'), ('repassage_seul', 'Repassage seul')], max_length=60),
        ),
    ]
