# Generated by Django 5.2.8 on 2026-01-13 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pressing_app', '0006_commande_etat_alter_commande_delai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetement',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
